export const photos = [
    {
        src: "https://static.todamateria.com.br/upload/og/ri/ogrito-cke.jpg",
        width: 2,
        height: 3,        
        title: "O grito",
        author: "Edvard Munch",
        estilo: "tipo 1",
        descricao: "WIP",
    },
    {
        src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Wassily_Kandinsky%2C_1903%2C_The_Blue_Rider_%28Der_Blaue_Reiter%29%2C_oil_on_canvas%2C_52.1_x_54.6_cm%2C_Stiftung_Sammlung_E.G._B%C3%BChrle%2C_Zurich.jpg/625px-Wassily_Kandinsky%2C_1903%2C_The_Blue_Rider_%28Der_Blaue_Reiter%29%2C_oil_on_canvas%2C_52.1_x_54.6_cm%2C_Stiftung_Sammlung_E.G._B%C3%BChrle%2C_Zurich.jpg",
        width: 3,
        height: 2,        
        title: "O cavaleiro azul",
        author: "Wassily Kandinsky",
        estilo: "tipo 1",
        descricao: "WIP",
    },
    {
        src: "https://static.todamateria.com.br/upload/po/rt/portinari-cke.jpg",
        width: 3,
        height: 3,        
        title: "Retirantes",
        author: "Portinari",
        estilo: "tipo 1",
        descricao: "WIP",
    },
    {
        src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Munch_Det_Syke_Barn_1896.jpg/275px-Munch_Det_Syke_Barn_1896.jpg",
        width: 2,
        height: 2,        
        title: "A Menina Doente",
        author: "Edvard Munch",
        estilo: "tipo 1",
        descricao: "WIP",
    },
    {
        src: "https://uploads5.wikiart.org/images/edvard-munch/despair-1892.jpg!Large.jpg",
        width: 2,
        height: 3,        
        title: "Desespero",
        author: "Edvard Munch",
        estilo: "tipo 2",
        descricao: "WIP",
    },
    {
        src: "https://ichef.bbci.co.uk/news/640/cpsprodpb/1251F/production/_106293057_525769e3-ee92-45f0-8f05-c6d154dcca7b.jpg",
        width: 3,
        height: 3,        
        title: "Abaporu",
        author: "Tarsila do Amaral",
        estilo: "tipo 2",
        descricao: "WIP",
    },
    {
        src: "https://cdn.culturagenial.com/imagens/anita-malfatti-cke.jpg",
        width: 3,
        height: 3,        
        title: "A Boba",
        author: "Anita Malfatti",
        estilo: "tipo 2",
        descricao: "WIP",
    },
    {
        src: "https://arteismos.files.wordpress.com/2014/03/dinamismo-de-um-automc3b3vel-umberto.jpg?w=700",
        width: 2,
        height: 1,        
        title: "O Dinamismo de um Automóvel",
        author: "Luigi Russolo",
        estilo: "tipo 2",
        descricao: "WIP",
    },
    {
        src: "https://i.pinsrc.com/originals/67/78/35/67783507c5c2b17282c5cf716f2811cf.jpg",
        width: 2,
        height: 1,        
        title: "Dinamismo de Um Cão na Coleira",
        author: "Giacomo Balla",
        estilo: "tipo 2",
        descricao: "WIP",
    },
    {
        src: "http://www.infoescola.com/wp-content/uploads/2009/08/guernica.jpg",
        width: 8,
        height: 2,
        title: "Guernica",
        author: "Picasso",
        estilo: "tipo 3",
        descricao: "WIP",
    },
    {
        src: "https://www.saiacomarte.com/wp-content/uploads/2017/02/Clio-Team-1907-Picasso-Les-Demoiselles-dAvignon-Young-ladies-of-Avignon-Huile-sur-Toile-2439x2337-cm-948x1024.jpg",
        width: 3,
        height: 2,
        title: "As senhoritas de Avignon",
        author: "Picasso",
        estilo: "tipo 3",
        descricao: "WIP",
    },
    {
        src: "https://upload.wikimedia.org/wikipedia/pt/5/59/A_Persist%C3%AAncia_da_Mem%C3%B3ria.jpg",
        width: 3,
        height: 2,
        title: "Persistência da memória",
        author: "Salvador Dalí",
        estilo: "tipo 3",
        descricao: "WIP",
    },
    {
        src: "https://i0.wp.com/www.historiadasartes.com/wp-content/uploads/2016/09/m_MagritteCachimbo.jpg?resize=640%2C477",
        width: 1,
        height: 1,
        title: "A traição das imagens",
        author: "René Magritte",
        estilo: "tipo 4",
        descricao: "WIP",
    },
    {
        src: "https://cdn.culturagenial.com/imagens/as-duas-fridas-frida-kahlo-cke.jpg",
        width: 3,
        height: 3,
        title: "As duas Fridas",
        author: "Frida Kahlo",
        estilo: "tipo 4",
        descricao: "WIP",
    },
    {
        src: "https://images.pexels.com/photos/6830152/pexels-photo-6830152.jpeg?cs=srgb&dl=pexels-paul-blenkhorn-sensoryarthouse-6830152.jpg&fm=jpg",
        width: 2,
        height: 4,
        title: "UNS TREM AI",
        author: "UM ZÉ AI",
        estilo: "tipo 4",
        descricao: "WIP",
    }
]

